version: '2'

volumes:
  orderer1.wayne-entreprises.com:
  orderer2.wayne-entreprises.com:
  peer0.asd.wayne-entreprises.com:
  peer1.asd.wayne-entreprises.com:
  peer2.asd.wayne-entreprises.com:


networks:
  asd_network:

services:
  ca.wayne-entreprises.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.wayne-entreprises.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.asd.wayne-entreprises.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CERT_FILENAME}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.asd.wayne-entreprises.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CERT_FILENAME}
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/asd.wayne-entreprises.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    container_name: ca.wayne-entreprises.com
    networks:
      - asd_network

  fabric-kafka:
    container_name: fabric-kafka
    image: hyperledger/fabric-kafka
    ports:
      - 9092
    hostname: fabric-kafka
    links:
      - fabric-zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=fabric-kafka
      - KAFKA_ZOOKEEPER_CONNECT=fabric-zookeeper:2181
      - KAFKA_ADVERTISED_PORT=9092
    networks:
      - asd_network

  fabric-zookeeper:
    container_name: fabric-zookeeper
    image: hyperledger/fabric-zookeeper
    ports:
      - "2181:2181"
    networks:
      - asd_network

  orderer1.wayne-entreprises.com:
    container_name: orderer1.wayne-entreprises.com
    depends_on:
      - fabric-kafka
    extends:
      file: base/docker-compose-base.yaml
      service: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/wayne-entreprises.com/orderers/orderer1.wayne-entreprises.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/wayne-entreprises.com/orderers/orderer1.wayne-entreprises.com/tls/:/var/hyperledger/orderer/tls
      - orderer1.wayne-entreprises.com:/var/hyperledger/production/orderer
    networks:
      - asd_network
    ports:
      - 7050:7050

  orderer2.wayne-entreprises.com:
    container_name: orderer2.wayne-entreprises.com
    depends_on:
      - fabric-kafka
    extends:
      file: base/docker-compose-base.yaml
      service: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/wayne-entreprises.com/orderers/orderer2.wayne-entreprises.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/wayne-entreprises.com/orderers/orderer2.wayne-entreprises.com/tls/:/var/hyperledger/orderer/tls
      - orderer2.wayne-entreprises.com:/var/hyperledger/production/orderer
    networks:
      - asd_network
    ports:
      - 8050:7050

  peer0.asd.wayne-entreprises.com:
    container_name: peer0.asd.wayne-entreprises.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0
      - CORE_PEER_ADDRESS=peer0.asd.wayne-entreprises.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.asd.wayne-entreprises.com:7051
    volumes:
       - ./crypto-config/peerOrganizations/asd.wayne-entreprises.com/peers/peer0.asd.wayne-entreprises.com/msp:/etc/hyperledger/fabric/msp
       - ./crypto-config/peerOrganizations/asd.wayne-entreprises.com/peers/peer0.asd.wayne-entreprises.com/tls:/etc/hyperledger/fabric/tls
       - peer0.asd.wayne-entreprises.com:/var/hyperledger/production
    networks:
      - asd_network
    ports:
      - 7051:7051
      - 7053:7053

  peer1.asd.wayne-entreprises.com:
    container_name: peer1.asd.wayne-entreprises.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer1
      - CORE_PEER_ADDRESS=peer1.asd.wayne-entreprises.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.asd.wayne-entreprises.com:7051
    volumes:
       - ./crypto-config/peerOrganizations/asd.wayne-entreprises.com/peers/peer1.asd.wayne-entreprises.com/msp:/etc/hyperledger/fabric/msp
       - ./crypto-config/peerOrganizations/asd.wayne-entreprises.com/peers/peer1.asd.wayne-entreprises.com/tls:/etc/hyperledger/fabric/tls
       - peer1.asd.wayne-entreprises.com:/var/hyperledger/production
    networks:
      - asd_network
    ports:
      - 8051:7051
      - 8053:7053

  peer2.asd.wayne-entreprises.com:
    container_name: peer2.asd.wayne-entreprises.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer2
      - CORE_PEER_ADDRESS=peer2.asd.wayne-entreprises.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.asd.wayne-entreprises.com:7051
    volumes:
       - ./crypto-config/peerOrganizations/asd.wayne-entreprises.com/peers/peer2.asd.wayne-entreprises.com/msp:/etc/hyperledger/fabric/msp
       - ./crypto-config/peerOrganizations/asd.wayne-entreprises.com/peers/peer2.asd.wayne-entreprises.com/tls:/etc/hyperledger/fabric/tls
       - peer2.asd.wayne-entreprises.com:/var/hyperledger/production
    networks:
      - asd_network
    ports:
      - 9051:7051
      - 9053:7053

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.asd.wayne-entreprises.com:7051
      - CORE_PEER_LOCALMSPID=ASDOrgMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/crypto-config/peerOrganizations/asd.wayne-entreprises.com/peers/peer0.asd.wayne-entreprises.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/crypto-config/peerOrganizations/asd.wayne-entreprises.com/peers/peer0.asd.wayne-entreprises.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/crypto-config/peerOrganizations/asd.wayne-entreprises.com/peers/peer0.asd.wayne-entreprises.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/crypto-config/peerOrganizations/asd.wayne-entreprises.com/users/Admin@asd.wayne-entreprises.com/msp
      - CA_FILE=/opt/gopath/crypto-config/ordererOrganizations/wayne-entreprises.com/orderers/orderer1.wayne-entreprises.com/msp/tlscacerts/tlsca.wayne-entreprises.com-cert.pem
      - CHANNEL_NAME=asdchannel
    working_dir: /opt/gopath
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode:/opt/gopath/src/chaincode
        - ./crypto-config:/opt/gopath/crypto-config
        - ./scripts:/opt/gopath/scripts/
        - ./channel-artifacts:/opt/gopath/channel-artifacts
    depends_on:
      - orderer1.wayne-entreprises.com
      - orderer2.wayne-entreprises.com
      - peer0.asd.wayne-entreprises.com
      - peer1.asd.wayne-entreprises.com
      - peer2.asd.wayne-entreprises.com
    networks:
      - asd_network
